/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HireguardResumes": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "HireguardSesIdentity": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "PdfExtract": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SesAlert": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "StatsCompute": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}

import "sst"
export {}